/**
 * Partial translation dictionary (merged into the main DICT in i18n.tsx).
 * Keyed by the English source string. Fill fr/ko/es. Cubing terms
 * (Ao5, WCA, 3x3, Megaminx, Pyraminx) stay as-is. No em dashes.
 */
export const dict: Record<"fr" | "ko" | "es", Record<string, string>> = {
  fr: {
    // CompTimer
    "Solve": "Résolution",
    "of": "sur",
    "8 seconds": "8 secondes",
    "12 seconds": "12 secondes",
    "Tap to start inspection.": "Touchez pour lancer l'inspection.",
    "Press space to start inspection.": "Appuyez sur espace pour lancer l'inspection.",
    "Tap the screen to start. Tap again to stop.": "Touchez l'écran pour démarrer. Touchez à nouveau pour arrêter.",
    "Press space to start. Press any key to stop.": "Appuyez sur espace pour démarrer. Appuyez sur n'importe quelle touche pour arrêter.",
    "Hold the screen, release to start. Tap to stop.": "Maintenez l'écran, relâchez pour démarrer. Touchez pour arrêter.",
    "Hold space, release to start. Any key to stop.": "Maintenez espace, relâchez pour démarrer. N'importe quelle touche pour arrêter.",
    "Inspecting. Hold, release to start your solve.": "Inspection. Maintenez, relâchez pour lancer votre résolution.",
    "Inspecting. Hold space, release to start your solve.": "Inspection. Maintenez espace, relâchez pour lancer votre résolution.",
    "Keep holding": "Continuez à maintenir",
    "Release to start": "Relâchez pour démarrer",
    "Scramble group": "Groupe de mélange",
    "Group": "Groupe",
    "Switch to Group": "Passer au groupe",
    "solve will be cleared.": "résolution sera effacée.",
    "solves will be cleared.": "résolutions seront effacées.",
    "Feedback": "Retour",
    "Report a bug or suggest an idea": "Signaler un bug ou proposer une idée",
    "Found something broken, or have an idea to make Cube Bench better? Tell us here.":
      "Quelque chose ne fonctionne pas, ou vous avez une idée pour améliorer Cube Bench ? Dites-le nous ici.",
    "Feedback type": "Type de retour",
    "Bug": "Bug",
    "Suggestion": "Suggestion",
    "What went wrong?": "Qu'est-ce qui n'a pas marché ?",
    "What's your idea?": "Quelle est votre idée ?",
    "What did you do, and what happened instead?":
      "Qu'avez-vous fait, et que s'est-il passé à la place ?",
    "Describe what you'd like to see.": "Décrivez ce que vous aimeriez voir.",
    "Email (optional, for a reply)": "E-mail (facultatif, pour une réponse)",
    "Send feedback": "Envoyer",
    "Sending…": "Envoi…",
    "Thanks, we got it.": "Merci, c'est bien reçu.",
    "Every report and idea is read. If you left an email we'll reach out when it helps.":
      "Chaque rapport et idée est lu. Si vous avez laissé un e-mail, nous vous recontacterons si besoin.",
    "Send another": "En envoyer un autre",
    "Please add a little more detail.": "Ajoutez un peu plus de détails.",
    "Something went wrong. Please try again.":
      "Une erreur s'est produite. Veuillez réessayer.",
    "Report a bug or suggest something": "Signaler un bug ou proposer une idée",
    "Over 15 seconds. This solve is +2. Start when ready.": "Plus de 15 secondes. Cette résolution est +2. Démarrez quand vous êtes prêt.",
    "Inspecting. Tap to start your solve.": "Inspection. Touchez pour lancer votre résolution.",
    "Inspecting. Press space to start your solve.": "Inspection. Appuyez sur espace pour lancer votre résolution.",
    "Tap to stop": "Touchez pour arrêter",
    "Any key to stop": "N'importe quelle touche pour arrêter",
    "Marked as DNF, so it won't count as a time": "Marqué DNF, il ne comptera donc pas comme un temps",
    "Inspection ran past 15 seconds. +2 included (stopwatch read": "L'inspection a dépassé 15 secondes. +2 inclus (chrono affiché",
    "+2 applied (stopwatch read": "+2 appliqué (chrono affiché",
    "Solve complete": "Résolution terminée",
    "Discard this attempt and solve the same scramble again": "Annuler cette tentative et résoudre à nouveau le même mélange",
    "Redo": "Recommencer",
    "Automatic: inspection ran past 15 seconds": "Automatique : l'inspection a dépassé 15 secondes",
    "Mark a +2 penalty on this attempt": "Marquer une pénalité +2 sur cette tentative",
    "+2": "+2",
    "Mark this attempt as Did Not Finish": "Marquer cette tentative comme non terminée (DNF)",
    "DNF": "DNF",
    "Solve again": "Résoudre à nouveau",
    "See your ranking": "Voir votre classement",
    "Next solve": "Résolution suivante",
    // Solving
    "Back": "Retour",
    "Times so far": "Temps jusqu'ici",
    "Timer mode": "Mode du chrono",
    "Regular": "Standard",
    "Skill Timer": "Chrono par étapes",
    "Soon": "Bientôt",
    "Skill Timer (stage splits) is a work in progress.": "Le chrono par étapes (temps intermédiaires) est en cours de développement.",
    "Running": "En cours",
    "This round": "Ce tour",
    "done": "faites",
    "Who you're up against": "À qui vous vous mesurez",
    "in the field": "en lice",
    "fastest average": "meilleure moyenne",
    "advance to the": "se qualifient pour le",
    // Simulator
    "Discard your paused round at": "Abandonner votre tour en pause à",
    "solve will be lost.": "résolution sera perdue.",
    "solves will be lost.": "résolutions seront perdues.",
    "Paused round": "Tour en pause",
    "solves done": "résolutions faites",
    "Resume": "Reprendre",
    "Discard": "Abandonner",
    "Competitions": "Compétitions",
    "Step 2": "Étape 2",
    "Choose an event": "Choisissez une épreuve",
    "held": "a proposé",
    "event you can simulate. Pick one to see its rounds.": "épreuve que vous pouvez simuler. Choisissez-en une pour voir ses tours.",
    "events you can simulate. Pick one to see its rounds.": "épreuves que vous pouvez simuler. Choisissez-en une pour voir ses tours.",
    "Mean of 3": "Moyenne de 3",
    "Average of 5": "Moyenne de 5",
    "Blindfolded and Fewest Moves events aren't supported yet.": "Les épreuves à l'aveugle et Fewest Moves ne sont pas encore prises en charge.",
    "Step 3": "Étape 3",
    "Choose a round": "Choisissez un tour",
    "ran": "a organisé",
    "round of": "tour de",
    "rounds of": "tours de",
    "Solve any of them. Later rounds rank you against the field that advanced.": "Résolvez celui de votre choix. Les tours suivants vous classent face aux concurrents qualifiés.",
    "everyone": "tout le monde",
    "advanced": "qualifiés",
    "You made the cut": "Vous êtes qualifié",
    "Congratulations!": "Félicitations !",
    "You qualified for the": "Vous vous êtes qualifié pour le",
    "Only the fastest advanced. Solve their scrambles and see if you'd hold your ground.": "Seuls les plus rapides se sont qualifiés. Résolvez leurs mélanges et voyez si vous tiendriez la distance.",
    "Try again": "Réessayer",
    "Start the": "Commencer le",
    "Loading scrambles…": "Chargement des mélanges…",
    "Back to results": "Retour aux résultats",
  },
  ko: {
    // CompTimer
    "Solve": "풀이",
    "of": "/",
    "8 seconds": "8초",
    "12 seconds": "12초",
    "Tap to start inspection.": "탭하여 검토를 시작하세요.",
    "Press space to start inspection.": "스페이스바를 눌러 검토를 시작하세요.",
    "Tap the screen to start. Tap again to stop.": "화면을 탭하여 시작하세요. 다시 탭하여 멈추세요.",
    "Press space to start. Press any key to stop.": "스페이스바를 눌러 시작하세요. 아무 키나 눌러 멈추세요.",
    "Hold the screen, release to start. Tap to stop.": "화면을 길게 누른 뒤 떼면 시작됩니다. 탭하여 멈추세요.",
    "Hold space, release to start. Any key to stop.": "스페이스바를 누른 뒤 떼면 시작됩니다. 아무 키나 눌러 멈추세요.",
    "Inspecting. Hold, release to start your solve.": "검토 중입니다. 길게 누른 뒤 떼면 풀이가 시작됩니다.",
    "Inspecting. Hold space, release to start your solve.": "검토 중입니다. 스페이스바를 누른 뒤 떼면 풀이가 시작됩니다.",
    "Keep holding": "계속 누르세요",
    "Release to start": "떼면 시작됩니다",
    "Scramble group": "스크램블 그룹",
    "Group": "그룹",
    "Switch to Group": "다음 그룹으로 전환:",
    "solve will be cleared.": "개의 풀이가 사라집니다.",
    "solves will be cleared.": "개의 풀이가 사라집니다.",
    "Feedback": "피드백",
    "Report a bug or suggest an idea": "버그 신고 또는 아이디어 제안",
    "Found something broken, or have an idea to make Cube Bench better? Tell us here.":
      "문제가 있거나 Cube Bench를 개선할 아이디어가 있나요? 여기서 알려주세요.",
    "Feedback type": "피드백 유형",
    "Bug": "버그",
    "Suggestion": "제안",
    "What went wrong?": "무엇이 잘못되었나요?",
    "What's your idea?": "어떤 아이디어인가요?",
    "What did you do, and what happened instead?":
      "무엇을 했고, 대신 어떤 일이 일어났나요?",
    "Describe what you'd like to see.": "보고 싶은 기능을 설명해 주세요.",
    "Email (optional, for a reply)": "이메일 (선택, 답장용)",
    "Send feedback": "보내기",
    "Sending…": "보내는 중…",
    "Thanks, we got it.": "감사합니다, 잘 받았습니다.",
    "Every report and idea is read. If you left an email we'll reach out when it helps.":
      "모든 신고와 아이디어를 읽습니다. 이메일을 남기셨다면 필요할 때 연락드리겠습니다.",
    "Send another": "다시 보내기",
    "Please add a little more detail.": "조금 더 자세히 적어주세요.",
    "Something went wrong. Please try again.": "문제가 발생했습니다. 다시 시도해 주세요.",
    "Report a bug or suggest something": "버그 신고 또는 제안하기",
    "Over 15 seconds. This solve is +2. Start when ready.": "15초를 초과했습니다. 이 풀이는 +2입니다. 준비되면 시작하세요.",
    "Inspecting. Tap to start your solve.": "검토 중입니다. 탭하여 풀이를 시작하세요.",
    "Inspecting. Press space to start your solve.": "검토 중입니다. 스페이스바를 눌러 풀이를 시작하세요.",
    "Tap to stop": "탭하여 멈추기",
    "Any key to stop": "아무 키나 눌러 멈추기",
    "Marked as DNF, so it won't count as a time": "DNF로 표시되어 기록에 반영되지 않습니다",
    "Inspection ran past 15 seconds. +2 included (stopwatch read": "검토가 15초를 초과했습니다. +2 포함 (스톱워치 기록",
    "+2 applied (stopwatch read": "+2 적용 (스톱워치 기록",
    "Solve complete": "풀이 완료",
    "Discard this attempt and solve the same scramble again": "이 시도를 취소하고 같은 스크램블을 다시 풀기",
    "Redo": "다시 하기",
    "Automatic: inspection ran past 15 seconds": "자동: 검토가 15초를 초과했습니다",
    "Mark a +2 penalty on this attempt": "이 시도에 +2 페널티 표시",
    "+2": "+2",
    "Mark this attempt as Did Not Finish": "이 시도를 DNF로 표시",
    "DNF": "DNF",
    "Solve again": "다시 풀기",
    "See your ranking": "순위 보기",
    "Next solve": "다음 풀이",
    // Solving
    "Back": "뒤로",
    "Times so far": "지금까지의 기록",
    "Timer mode": "타이머 모드",
    "Regular": "일반",
    "Skill Timer": "스킬 타이머",
    "Soon": "곧 제공",
    "Skill Timer (stage splits) is a work in progress.": "스킬 타이머(단계별 기록)는 개발 중입니다.",
    "Running": "진행 중",
    "This round": "이 라운드",
    "done": "완료",
    "Who you're up against": "경쟁 상대",
    "in the field": "참가자",
    "fastest average": "최고 평균",
    "advance to the": "다음 라운드 진출:",
    // Simulator
    "Discard your paused round at": "일시정지된 라운드를 삭제할까요:",
    "solve will be lost.": "번의 풀이가 사라집니다.",
    "solves will be lost.": "번의 풀이가 사라집니다.",
    "Paused round": "일시정지된 라운드",
    "solves done": "풀이 완료",
    "Resume": "이어서 하기",
    "Discard": "삭제",
    "Competitions": "대회",
    "Step 2": "2단계",
    "Choose an event": "종목 선택",
    "held": "대회에서 진행한",
    "event you can simulate. Pick one to see its rounds.": "개의 종목을 시뮬레이션할 수 있습니다. 하나를 선택해 라운드를 확인하세요.",
    "events you can simulate. Pick one to see its rounds.": "개의 종목을 시뮬레이션할 수 있습니다. 하나를 선택해 라운드를 확인하세요.",
    "Mean of 3": "3회 평균",
    "Average of 5": "5회 평균",
    "Blindfolded and Fewest Moves events aren't supported yet.": "블라인드폴드 및 Fewest Moves 종목은 아직 지원되지 않습니다.",
    "Step 3": "3단계",
    "Choose a round": "라운드 선택",
    "ran": "대회에서 진행한",
    "round of": "라운드 (종목:",
    "rounds of": "라운드 (종목:",
    "Solve any of them. Later rounds rank you against the field that advanced.": "원하는 라운드를 풀어보세요. 이후 라운드에서는 진출한 참가자들과 순위를 겨룹니다.",
    "everyone": "전원",
    "advanced": "진출자",
    "You made the cut": "통과했습니다",
    "Congratulations!": "축하합니다!",
    "You qualified for the": "다음 라운드에 진출했습니다:",
    "Only the fastest advanced. Solve their scrambles and see if you'd hold your ground.": "가장 빠른 참가자만 진출했습니다. 그들의 스크램블을 풀어보고 당신의 실력이 통하는지 확인하세요.",
    "Try again": "다시 시도",
    "Start the": "시작:",
    "Loading scrambles…": "스크램블 불러오는 중…",
    "Back to results": "결과로 돌아가기",
  },
  es: {
    // CompTimer
    "Solve": "Resolución",
    "of": "de",
    "8 seconds": "8 segundos",
    "12 seconds": "12 segundos",
    "Tap to start inspection.": "Toca para iniciar la inspección.",
    "Press space to start inspection.": "Pulsa espacio para iniciar la inspección.",
    "Tap the screen to start. Tap again to stop.": "Toca la pantalla para empezar. Toca de nuevo para parar.",
    "Press space to start. Press any key to stop.": "Pulsa espacio para empezar. Pulsa cualquier tecla para parar.",
    "Hold the screen, release to start. Tap to stop.": "Mantén la pantalla, suelta para empezar. Toca para parar.",
    "Hold space, release to start. Any key to stop.": "Mantén espacio, suelta para empezar. Cualquier tecla para parar.",
    "Inspecting. Hold, release to start your solve.": "Inspeccionando. Mantén, suelta para iniciar tu resolución.",
    "Inspecting. Hold space, release to start your solve.": "Inspeccionando. Mantén espacio, suelta para iniciar tu resolución.",
    "Keep holding": "Sigue manteniendo",
    "Release to start": "Suelta para empezar",
    "Scramble group": "Grupo de mezclas",
    "Group": "Grupo",
    "Switch to Group": "¿Cambiar al grupo",
    "solve will be cleared.": "resolución se borrará.",
    "solves will be cleared.": "resoluciones se borrarán.",
    "Feedback": "Comentarios",
    "Report a bug or suggest an idea": "Reportar un error o sugerir una idea",
    "Found something broken, or have an idea to make Cube Bench better? Tell us here.":
      "¿Encontraste algo roto o tienes una idea para mejorar Cube Bench? Cuéntanos aquí.",
    "Feedback type": "Tipo de comentario",
    "Bug": "Error",
    "Suggestion": "Sugerencia",
    "What went wrong?": "¿Qué salió mal?",
    "What's your idea?": "¿Cuál es tu idea?",
    "What did you do, and what happened instead?":
      "¿Qué hiciste y qué pasó en su lugar?",
    "Describe what you'd like to see.": "Describe lo que te gustaría ver.",
    "Email (optional, for a reply)": "Correo (opcional, para responder)",
    "Send feedback": "Enviar",
    "Sending…": "Enviando…",
    "Thanks, we got it.": "Gracias, lo recibimos.",
    "Every report and idea is read. If you left an email we'll reach out when it helps.":
      "Leemos cada reporte e idea. Si dejaste un correo, te contactaremos cuando sea útil.",
    "Send another": "Enviar otro",
    "Please add a little more detail.": "Añade un poco más de detalle.",
    "Something went wrong. Please try again.": "Algo salió mal. Inténtalo de nuevo.",
    "Report a bug or suggest something": "Reportar un error o sugerir algo",
    "Over 15 seconds. This solve is +2. Start when ready.": "Más de 15 segundos. Esta resolución es +2. Empieza cuando quieras.",
    "Inspecting. Tap to start your solve.": "Inspeccionando. Toca para iniciar tu resolución.",
    "Inspecting. Press space to start your solve.": "Inspeccionando. Pulsa espacio para iniciar tu resolución.",
    "Tap to stop": "Toca para parar",
    "Any key to stop": "Cualquier tecla para parar",
    "Marked as DNF, so it won't count as a time": "Marcado como DNF, así que no contará como tiempo",
    "Inspection ran past 15 seconds. +2 included (stopwatch read": "La inspección superó los 15 segundos. +2 incluido (cronómetro marcó",
    "+2 applied (stopwatch read": "+2 aplicado (cronómetro marcó",
    "Solve complete": "Resolución completada",
    "Discard this attempt and solve the same scramble again": "Descartar este intento y resolver el mismo scramble de nuevo",
    "Redo": "Repetir",
    "Automatic: inspection ran past 15 seconds": "Automático: la inspección superó los 15 segundos",
    "Mark a +2 penalty on this attempt": "Marcar una penalización +2 en este intento",
    "+2": "+2",
    "Mark this attempt as Did Not Finish": "Marcar este intento como no terminado (DNF)",
    "DNF": "DNF",
    "Solve again": "Resolver de nuevo",
    "See your ranking": "Ver tu clasificación",
    "Next solve": "Siguiente resolución",
    // Solving
    "Back": "Atrás",
    "Times so far": "Tiempos hasta ahora",
    "Timer mode": "Modo del cronómetro",
    "Regular": "Normal",
    "Skill Timer": "Cronómetro por fases",
    "Soon": "Pronto",
    "Skill Timer (stage splits) is a work in progress.": "El cronómetro por fases (tiempos parciales) está en desarrollo.",
    "Running": "En curso",
    "This round": "Esta ronda",
    "done": "hechas",
    "Who you're up against": "Contra quién compites",
    "in the field": "en competencia",
    "fastest average": "mejor promedio",
    "advance to the": "avanzan a la",
    // Simulator
    "Discard your paused round at": "¿Descartar tu ronda en pausa en",
    "solve will be lost.": "resolución se perderá.",
    "solves will be lost.": "resoluciones se perderán.",
    "Paused round": "Ronda en pausa",
    "solves done": "resoluciones hechas",
    "Resume": "Reanudar",
    "Discard": "Descartar",
    "Competitions": "Competiciones",
    "Step 2": "Paso 2",
    "Choose an event": "Elige una modalidad",
    "held": "tuvo",
    "event you can simulate. Pick one to see its rounds.": "modalidad que puedes simular. Elige una para ver sus rondas.",
    "events you can simulate. Pick one to see its rounds.": "modalidades que puedes simular. Elige una para ver sus rondas.",
    "Mean of 3": "Media de 3",
    "Average of 5": "Promedio de 5",
    "Blindfolded and Fewest Moves events aren't supported yet.": "Las modalidades a ciegas y Fewest Moves aún no son compatibles.",
    "Step 3": "Paso 3",
    "Choose a round": "Elige una ronda",
    "ran": "tuvo",
    "round of": "ronda de",
    "rounds of": "rondas de",
    "Solve any of them. Later rounds rank you against the field that advanced.": "Resuelve la que quieras. Las rondas posteriores te clasifican frente a quienes avanzaron.",
    "everyone": "todos",
    "advanced": "avanzaron",
    "You made the cut": "Pasaste el corte",
    "Congratulations!": "¡Felicidades!",
    "You qualified for the": "Te clasificaste para la",
    "Only the fastest advanced. Solve their scrambles and see if you'd hold your ground.": "Solo avanzaron los más rápidos. Resuelve sus scrambles y comprueba si aguantarías el ritmo.",
    "Try again": "Intentar de nuevo",
    "Start the": "Comenzar la",
    "Loading scrambles…": "Cargando scrambles…",
    "Back to results": "Volver a los resultados",
  },
};
